version: "3.8"

services:
  blue:
    image: ${IMAGE_NAME}:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__ApplicationDBConnectionString=${ConnectionStrings__ApplicationDBConnectionString}
      - ConnectionStrings__ISGrantDBConnectionString=${ConnectionStrings__ISGrantDBConnectionString}
      - ConnectionStrings__ISConfigDBConnectionString=${ConnectionStrings__ISConfigDBConnectionString}
      - ConnectionStrings__Redis=${ConnectionStrings__Redis}
      - RedisServer__RedisCacheConfiguration=${RedisServer__RedisCacheConfiguration}
      - RedisServer__RedisInstanceName=${RedisServer__RedisInstanceName}
      - RedisServer__ConnectionMultiplexer=${RedisServer__ConnectionMultiplexer}
    container_name: ${CONTAINER_PROJECT_NAME}-blue # Now dynamic!
    restart: unless-stopped
    ports:
      - "${BLUE_PORT}:80"
    networks:
      - grrnet

  green:
    image: ${IMAGE_NAME}:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__ApplicationDBConnectionString=${ConnectionStrings__ApplicationDBConnectionString}
      - ConnectionStrings__ISGrantDBConnectionString=${ConnectionStrings__ISGrantDBConnectionString}
      - ConnectionStrings__ISConfigDBConnectionString=${ConnectionStrings__ISConfigDBConnectionString}
      - ConnectionStrings__Redis=${ConnectionStrings__Redis}
      - RedisServer__RedisCacheConfiguration=${RedisServer__RedisCacheConfiguration}
      - RedisServer__RedisInstanceName=${RedisServer__RedisInstanceName}
      - RedisServer__ConnectionMultiplexer=${RedisServer__ConnectionMultiplexer}
    container_name: ${CONTAINER_PROJECT_NAME}-green # Now dynamic!
    restart: unless-stopped
    ports:
      - "${GREEN_PORT}:80"
    networks:
      - grrnet

networks:
  grrnet:
    name: grrnet
    external: true
